import type { Metadata } from "next";
import { PageShell } from "@/components/layout/PageShell";
import { buildMetadata } from "@/lib/seo/metadata";
import { siteConfig } from "@/lib/site-config";

export const metadata: Metadata = buildMetadata({
  path: "/privacy/",
  title: "Privacy Policy",
  description:
    "What AssessCheck collects (very little), what it deliberately does not collect, how Google advertising would change that, and your rights.",
  publishStatus: "ready",
  lastVerifiedDate: "2026-09-17",
  section: "Legal",
});

export default function PrivacyPage() {
  const updated = siteConfig.legal.lastUpdated.privacy;
  return (
    <PageShell breadcrumbs={[{ label: "Legal" }, { label: "Privacy policy" }]}>
      <h1>Privacy Policy</h1>
      <p>
        Last updated: <time dateTime={updated}>{updated}</time>
      </p>

      <h2>Who is responsible</h2>
      <p>
        This site ({siteConfig.name}) is created and maintained by{" "}
        {siteConfig.author.name}, who is the person responsible for its
        content and for handling any privacy request related to it — see{" "}
        <a href="/about/author/">about the author</a>. There is no separate
        company, data protection officer, or legal department behind this
        site, and we do not claim one.
      </p>

      <h2>What this site collects today: the short answer</h2>
      <p>
        <strong>Almost nothing, and nothing about you personally.</strong>{" "}
        There is no account system, no analytics script, no advertising
        script, and no cookies set by this site (see the{" "}
        <a href="/cookie-policy/">cookie policy</a>).
      </p>

      <h2>The assessment checker</h2>
      <p>
        The checker (<a href="/property-tax-checker/">state edition</a> and{" "}
        <a href="/texas/harris-county/property-tax-checker/">Harris County
        edition</a>) runs entirely in your browser. The values you enter —
        appraised values, property characteristics, condition notes — are
        processed in browser memory to produce your on-screen review. They are
        <strong> not transmitted to us, not stored on our servers, and not
        visible to anyone else</strong>. Closing the page discards them.
      </p>

      <h2>Information you send voluntarily</h2>
      <p>
        The only situation in which we receive personal information is when
        you send it to us yourself through the <a href="/contact/">contact
        page</a> — for example, your email address and the content of your
        message. That information is used solely to respond to your report or
        request, is not added to any mailing list, and is not shared with
        third parties except where strictly necessary to address your message
        or required by law.
      </p>

      <h2>Technical data</h2>
      <p>
        Like virtually all websites, this site is served through hosting
        infrastructure that may generate standard technical logs (for example,
        IP address, browser type, and request time) for security and
        operational purposes. These logs are generated by the hosting layer,
        not used by this site for tracking, and retained only for whatever
        limited period the hosting provider applies. We do not enrich,
        profile, or cross-reference this data.
      </p>

      <h2>Analytics</h2>
      <p>
        <strong>Not implemented.</strong> No analytics service runs on this
        site today. If that changes, this policy will be updated before the
        change goes live, and consent will be handled as described under
        &ldquo;Consent&rdquo; below.
      </p>

      <h2>Advertising and Google services</h2>
      <p>
        <strong>Advertising is not currently active.</strong> If{" "}
        {siteConfig.name} enables advertising, it is expected to use Google
        AdSense. When that happens, the following will apply and this section
        will be updated to reflect the live implementation:
      </p>
      <ul>
        <li>
          Google and its partners may use cookies or similar technologies to
          serve and measure advertising, and may read or store information in
          your browser;
        </li>
        <li>
          depending on your consent and settings, advertising may be
          personalized or non-personalized;
        </li>
        <li>
          where consent is required (including the EEA, the United Kingdom,
          and Switzerland), ads will respect the choice recorded in the
          consent mechanism, changeable at any time via{" "}
          <a href="/consent-preferences/">consent preferences</a>.
        </li>
      </ul>
      <p>
        Google's own explanation of how it uses data from sites and apps that
        use its partners' services is published here (official Google
        source):{" "}
        <a
          href="https://policies.google.com/technologies/partner-sites"
          target="_blank"
          rel="noopener noreferrer"
        >
          How Google uses information from sites or apps that use our services
        </a>
        . You can also review the <a href="/advertising-disclosure/">advertising
        disclosure</a>.
      </p>

      <h2>Third-party links</h2>
      <p>
        We link to official government sources (the Texas Comptroller, county
        appraisal districts, statutes). Following those links takes you to
        other domains with their own privacy practices, which we do not
        control and do not receive data from by virtue of your click.
      </p>

      <h2>Children</h2>
      <p>
        This site is intended for adult property owners and is not directed at
        children under 13, and we do not knowingly collect information from
        them.
      </p>

      <h2>Consent</h2>
      <p>
        Where consent is required for any future technology (advertising,
        analytics), it will be requested through a real, working consent
        mechanism before that technology runs; the choice will be honored
        site-wide and revocable at any time via{" "}
        <a href="/consent-preferences/">consent preferences</a>. We will not
        claim a consent regime we have not implemented.
      </p>

      <h2>Your rights</h2>
      <p>
        Because this site stores essentially nothing, there is usually nothing
        to access or delete — but the rights below are honored for the
        information you voluntarily send (for example, a contact message):
      </p>
      <ul>
        <li><strong>Access</strong> — ask what we hold that relates to you.</li>
        <li><strong>Rectification</strong> — ask us to correct it.</li>
        <li><strong>Deletion</strong> — ask us to delete it.</li>
        <li>
          <strong>Objection / restriction</strong> — ask us to stop a
          particular use.
        </li>
        <li>
          <strong>Portability</strong> — where it applies to voluntarily
          provided data, we will provide it in a usable format.
        </li>
      </ul>
      <p>
        Make any of these requests through the <a href="/contact/">contact
        page</a>. If you are in the EEA or UK and believe your rights have
        been infringed, you may also lodge a complaint with your national data
        protection authority.
      </p>

      <h2>Security</h2>
      <p>
        The site is served over HTTPS and contains no server-side storage of
        user data, which bounds what can be exposed: there is no user database
        to breach.
      </p>

      <h2>Changes to this policy</h2>
      <p>
        If this policy changes materially, the date at the top will be updated
        and the change summarized on our <a href="/corrections/">corrections
        page</a>. Substantive changes — especially anything enabling analytics
        or advertising — will be made <em>before</em> the underlying technology
        goes live.
      </p>
    </PageShell>
  );
}
